### ISSUE TITLE
Pre made container images

### ISSUE THREAD

**Issue by jaentwistle** [codercom/features#1]
It would be supremely cool if you can have different images for the containers ready for use. A lot of people would probably end up with web servers so if you can have an image with apache or nginx preinstalled that could be awesome :)

**Comment by Xenofuscus** [comment]
I think this could be implemented similarly to how we mount languages, although this method isn't exactly user friendly. If we come up with a better implementation for the squashfs mounting system we have in place, then this would be the way to go.

**Comment by Xenofuscus** [comment]
Forwarded to development for further consideration.

**Comment by Multishifties** [comment]
With the introduction of our self hosted offering, a user can host the IDE with a Dockerfile of their choice. 

@nol166 please close
