### ISSUE TITLE
Hide collaborator button for non owners

### ISSUE THREAD

**Issue by pokemonlover1234** [codercom/features#109]
**Is your feature request related to a problem? Please describe.**
Currently users who collaborate on a project can still see the collaborators button in the IDE, but it doesn't do anything if they don't own the project. I've heard Coder plans a more in-depth permission system, however the button should be hidden if the user in question does not have the ability to manage collaborators in the currently open project.

**Describe the solution you'd like**
Remove the collaborator management button in the IDE if the user does not have permission to manage the collaborators for the project that is currently open.

**Describe alternatives you've considered**
Making the button open the expected UI, but providing a message stating that they don't have permission to manage collaborators and the buttons grayed out.

**Comment by Multishifties** [comment]
Collaboration is now removed. @nol166 please close this issue
