### ISSUE TITLE
Support for edge

### ISSUE THREAD

**Issue by nol166** [codercom/features#112]
Sep 4, 2018 at 10:37:54 AM
### Suggested feature
A user is requesting edge support for coder's IDE. The user's corporation requires edge support in order for them to take advantage of coder's cloud-based services.

### Zendesk Ticket number
`944`

**Comment by Multishifties** [comment]
Microsoft is discontinuing Edge. We will not expend efforts into actively supporting a discontinued browser. https://www.theverge.com/2018/12/4/18125238/microsoft-chrome-browser-windows-10-edge-chromium

@nol166 please close.

**Comment by nol166** [comment]
RIP edge
