### ISSUE TITLE
Add "known issues" section to docs

### ISSUE THREAD

**Issue by pokemonlover1234** [codercom/features#117]
**Is your feature request related to a problem? Please describe.**
There are plenty of people who don't use or even know of the GitHub for reporting/viewing issues. However, the docs are a place they may go from time to time. Because of this, these users may not know that devs are aware of certain issues and may report them again instead of updated the GitHub issue. I've seen devs report duplicate feature requests/bug reports many times on the GitHub with a Zendesk issue reference when it would be better to update the original issue, as duplicates are usually closed. 

**Describe the solution you'd like**
A section on the docs called "known issues" to list issues that are currently known about and being worked on. This may reduce the number of duplicate bug reports and will allow users to know what issues to avoid even if they don't use GitHub.

**Describe alternatives you've considered**
Continuing to have known issues only be on the GitHub, and having a reference to this github on the docs mentioning that known issues are on this page.

**Additional context**
I know FIXED issues appear on the docs version pages along with a link to the corresponding GitHub issue, but those only refer to issues that are already fixed and not issues that are in the process of being fixed

**Comment by nol166** [comment]
This is a great idea

**Comment by rvrvrv** [comment]
We may eventually implement a **Known Issues** page on the docs. Thanks!

For now, the suggested alternative (link to [codercom/bugs](https://github.com/codercom/bugs/issues)) has been added to [Tech FAQs](https://docs.coder.com/docs/tech-faqs).

**Comment by Multishifties** [comment]
So, our docs are kinda removed from the website now. Most all issues can be found at https://github.com/codercom/code-server/issues

@nol166 please close this issue
