### ISSUE TITLE
Sync with GitHub/GitLab & quick-start flow

### ISSUE THREAD

**Issue by embiem** [codercom/features#123]
**Is your feature request related to a problem? Please describe.**
The problem: Imagine you quickly want to pick up an issue or develop a feature on a project, but first need to go through cloning the repo (maybe fork it first), checking out the correct branch, creating a new branch.

**Describe the solution you'd like**
Wouldn't it be awesome if coder would have a dedicated flow for these use cases, where one has to simply choose the repo, a branch name and then coder would set everything up (ultra fast) and the user can simply start coding?

To be able to fork the repo first (in case of e.g. Open Source), there also needs to be a GitHub/GitLab integration. This integration would also be useful to quickly select one of the user's repos.

**Describe alternatives you've considered**
A first step may be to actually allow creating projects from a repository url. Currently, I'd have to create a project in coder and then manually execute the steps mentioned above (cloning etc.)

**Additional context**
I see this as a nice to have feature, that I personally would find very useful. Also I believe that more people would contribute to Open Source, if they wouldn't have to care about the whole process needed before they can actually write a line of code.

**Comment by NGTmeaty** [comment]
I think this is a up-and coming feature(in-progress), but I would love to see it!

**Comment by nol166** [comment]
Another request via zendesk ```1364```

**Comment by jaymeramsay** [comment]
```ticket 1379```
