### ISSUE TITLE
QA: Add tags to projects/containers

### ISSUE THREAD

**Issue by nol166** [codercom/features#127]
**Is your feature request related to a problem? Please describe.**
No problem, in particular, would be nice to have

**Describe the solution you'd like**
It would be helpful for users with multiple projects/containers if they could have tags to easily separate them apart.

**Describe alternatives you've considered**
Trying to remember what project is named what.

**Additional context**
If we get enough requests for this we can definitely implement it.

**Comment by Multishifties** [comment]
projects/containers have been removed. @nol166 please close
