### ISSUE TITLE
Make paths in terminal clickable

### ISSUE THREAD

**Issue by AL1L** [codercom/features#132]
**Is your feature request related to a problem? Please describe.**
When a stack trace is printed to the console, that's when the debugging process starts. You have to read the trace, find the file, then go to the line and column it says where the error is.

**Describe the solution you'd like**
When a path is printed to the terminal (ie. `File "/coder/mnt/AL_1/MyApp/src/__main__.py", line 6, in <module>`), allow double-clicking and/or ctrl-clicking the path to open the file in the editor.

**Additional context**
![image](https://user-images.githubusercontent.com/8514986/47324552-ee99f000-d625-11e8-81d9-bb90d280d0f3.png)

**Comment by pokemonlover1234** [comment]
This sounds intersting!

**Comment by nol166** [comment]
I believe this is now possible in VSCode
