### ISSUE TITLE
Allow more than 256 characters in feedback form

### ISSUE THREAD

**Issue by nol166** [codercom/features#149]
**Is your feature request related to a problem? Please describe.**
256 characters are not enough for some when reporting bugs or providing feedback. We should rethink the way we are doing this to allow for longer messages.

**Describe the solution you'd like**
An option to exceed 256 characters in the zendesk feedback menu.

**Describe alternatives you've considered**
Using GitHub for feature requests and bugs, but it's not great for general feedback

**Additional context**
Request via zendesk `1484`

**Comment by Multishifties** [comment]
PR = https://github.com/codercom/frontend/pull/199

**Comment by Multishifties** [comment]
@nol166 please close. This has been resolved.
