### ISSUE TITLE
Atom style keyboard shortcuts

### ISSUE THREAD

**Issue by DavidMcKissick** [codercom/features#16]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
An option to add keybindings for:
1. Select line, Simply selects an entire line instantly.
2. Move selection, useful for reorganizing code quickly. See move line up/down https://github.com/nwinkler/atom-keyboard-shortcuts
**Describe alternatives you've considered**
None that come to mind

**Additional context**
So far that's the only major loss for me when using this vs something like say cloud9 or vs code (with atom keymap)

**Comment by Xenofuscus** [comment]
Forwarded to development team for further discussion.
