### ISSUE TITLE
Add button to restart container 

### ISSUE THREAD

**Issue by nol166** [codercom/features#164]
**Is your feature request related to a problem? Please describe.**
A user suggested that we have an option to restart the container in addition to toggling it off and then back on again.

**Describe the solution you'd like**
It would be cool if this could be done from multiple places in the UI (aka containers page and the IDE).

**Describe alternatives you've considered**
Toggling the container off and then on again

**Additional context**
zendesk `1468`

**Comment by Multishifties** [comment]
This button now exists under the `help` menu

@nol166 please close.
