### ISSUE TITLE
Shortcut: Move selected lines up or down

### ISSUE THREAD

**Issue by TheEvilSocks** [codercom/features#18]
**Is your feature request related to a problem? Please describe.**
Sometimes you write some code on the wrong line, or you've decided to refactor a small bit of already existing code and need to move some lines up or down into, for example an if block.

**Describe the solution you'd like**
(An option for ) a shortcut to move selected lines up or down in the IDE.

**Describe alternatives you've considered**
I mean cutting and pasting is an option, but I feel like directly moving lines would be way faster.

**Additional context**
Moving lines up or down is an existing feature in for example Sublime Text. Select a few lines and use ctrl+shift+⬆ or ctrl+shift+⬇

**Comment by Xenofuscus** [comment]
Related issue: #16
