### ISSUE TITLE
Container with more resources

### ISSUE THREAD

**Issue by MaxRenaud** [codercom/features#180]
Might be related to #14 
**Is your feature request related to a problem? Please describe.**
On more complex projects, FastTime is being used when everything is idle due to memory usage. This ends up using expensive FastTime for normal development as opposed to peak usage. This is actually a blocker for me to use this more.

**Describe the solution you'd like**
Allow the user to buy committed resources monthly at a price similar to what's available on the Google Cloud Platform. That could be a win-win. For example, take a n1-highmem-96 with 96 cores and 624gb of ram at a cost of 2.9k/month. Sell a plan with 3gb of ram for $15/month. Then when the container is not active or using the resources, you can use that committed resource for other people's FastTime. That way end users get a better deal than they'd get by purchasing small instances directly, AND you get to fund FastTime. Maybe do a bit like Amazon where users can earn FastTime credits (At a reduced rate) when they are not using their resources?

**Describe alternatives you've considered**
There are no viable alternatives. FastTime is an amazing idea and should be used for peak performance tasks like compiling, initial symbol loading, and tests. Having FastTime decrease just for having the IDE open and idle defeats the idea.

**Additional context**
Some users have expressed the idea to leave containers running and this can also help you I think. By letting the user buy resources at GCP rate AND giving reduced FastTime credit (maybe 25%?) for idle resources, you make your costs more predictable AND incentivize users to shut down unused containers to fund FastTime.

**Comment by Multishifties** [comment]
This is no longer relevant as of the release of the `code-server` repo. Users are now able to host their own instances of the IDE with any host of their choice and provide as many resources to their instance as they deem necessary.

@nol166 please close issue
