### ISSUE TITLE
Add ability to accept collab invites in the UI

### ISSUE THREAD

**Issue by nol166** [codercom/features#183]
**Is your feature request related to a problem? Please describe.**
Users have requested the ability to accept collab invitation from the UI without the need for going to their email

**Describe the solution you'd like**
Add an accept option in the UI for collab invites

**Describe alternatives you've considered**
Accepting via email

**Additional context**
zendesk `1822`

**Comment by Multishifties** [comment]
Collaboration has been disabled.

@nol166 please close.
