### ISSUE TITLE
Docs: text needs to be darker

### ISSUE THREAD

**Issue by jhalek90** [codercom/features#19]
**Is your feature request related to a problem? Please describe.**
The docs are a little hard to read because the main text color is grey on a white background.

**Describe the solution you'd like**
Black text is much easier to read on white backgrounds, and will result in less eye strain.

**Describe alternatives you've considered**
maybe just a darker grey?

**Additional context**
screen shot
![image](https://user-images.githubusercontent.com/13923704/43173554-136ea0de-8f7b-11e8-9ca6-16b365787a9f.png)

**Comment by rvrvrv** [comment]
Update: The lightest shades of gray have been darkened (slightly) across the docs.
