### ISSUE TITLE
Web hosting service

### ISSUE THREAD

**Issue by nol166** [codercom/features#192]
**Is your feature request related to a problem? Please describe.**
A user has requested that we add the ability to host a web app permanently. Currently, the container has to be on and the web server running for content to be hosted. It would be cool if we could offer a way to host without needing the container.
 
**Describe the solution you'd like**
See above

**Describe alternatives you've considered**
Using CDR.co for a limited time or another service like Heroku

**Additional context**
zendesk `2032`

**Comment by Multishifties** [comment]
Users can self host now with `code-server` allowing them the option to perma-host anything they want to.

@nol166 please close issue
