### ISSUE TITLE
Backend: mount ruby binaries when needed

### ISSUE THREAD

**Issue by deansheather** [codercom/features#21]
**Describe the solution you'd like**
Ruby should be mounted when the user needs it. RVM could also be mounted with a default Ruby version installed and active by default. The shared mount could possibly have all versions of ruby preinstalled for instant switching?

**Describe alternatives you've considered**
For now, users can install Ruby themselves using RVM or other means.

**Additional context**
Suggested via Zendesk.

**Comment by Xenofuscus** [comment]
This process should be automated by the IDE, and is similar to issue #10 with cpp libraries not loading. Thus this issue will be tracked similarly.
