### ISSUE TITLE
IDE: Allow drag-n-drop files from my local file system to the IDE

### ISSUE THREAD

**Issue by lobsterhands** [codercom/features#24]
**Is your feature request related to a problem? Please describe.**
It is inconvenient to set up an FTP solution to transfer files.

**Describe the solution you'd like**
I would like to be able to drag/drop files from my local file system to Coder's IDE.

**Comment by T0TProduction** [comment]
maybe in both directions, so also allow dragging files from the IDE into local folders.
if that isn't possible, at least right-click and download would be cool

**Comment by deansheather** [comment]
This is being worked on.

**Comment by jaymeramsay** [comment]
We're happy to say that this has been implemented!
