### ISSUE TITLE
IDE: Code live templates 

### ISSUE THREAD

**Issue by ReconCubed** [codercom/features#25]
**Describe the solution you'd like**
Ability to create live templates (like IntelliJ and other editors, https://www.jetbrains.com/help/idea/using-live-templates.html)

**Describe alternatives you've considered**
Copy n paste?

**Additional context**
https://www.jetbrains.com/help/idea/using-live-templates.html
https://www.jetbrains.com/help/idea/template-variables.html

**Comment by foresthoffman** [comment]
Thank you for your request, I've noted this internally. You can keep an eye on this issue, and it will be updated accordingly.

Best,
Forest
