### ISSUE TITLE
Docs: more language guides (such as C++)

### ISSUE THREAD

**Issue by deansheather** [codercom/features#27]
**Describe the solution you'd like**
More language guides for supported languages in the documentation: https://docs.coder.com/docs/language-guides.

**Describe alternatives you've considered**
n/a

**Additional context**
Requested via Zendesk.

**Comment by rvrvrv** [comment]
New language guides (including C++) are in the works and ready to be released w/additional language support in the IDE.

**Comment by nol166** [comment]
Language guides have been deprecated
