### ISSUE TITLE
The ability to paste text into the terminal.

### ISSUE THREAD

**Issue by DavidMcKissick** [codercom/features#29]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The ability to either use ctrl+v or right click then paste to paste text such as git repositories for cloning and complex generic  commands in the terminal

**Describe alternatives you've considered**
Manually typing the command in

**Additional context**
N/A

**Comment by foresthoffman** [comment]
@DavidMcKissick Hello, this may actually be a bug. Could you please provide me with the following information?

- Your OS and Version (e.g. Windows 10)
- Your Browser and Version (e.g. Chrome 67.0)

**Comment by DavidMcKissick** [comment]
OS: ChromeOS v69.0.3494.0 (Dev channel, Previously on 67.xx)
Browser: Chrome 69.0.3494.0 (Directly tied to the OS)

This issue was also present on ChromeOS on version 67.0.3396.99 (Browser of same ver.)
(Platform version: 10575.58.0) 

Architecture is arm32

**Comment by foresthoffman** [comment]
Does `CTRL+SHIFT+V` work for you?

**Comment by DavidMcKissick** [comment]
That works yes. Sorry about that, thanks for the assistance.

**Comment by foresthoffman** [comment]
My pleasure!

**Comment by ishanvyas22** [comment]
Unable to paste into terminal using cmd:

> CTRL+SHIFT+V

- OS : Lubuntu 18.04 (32-bit)
- Browser : Firefox Quantum 61.0.1 (32-bit)
