### ISSUE TITLE
Verification: say coder.com in the SMS verification

### ISSUE THREAD

**Issue by deansheather** [codercom/features#31]
**Describe the solution you'd like**
Account verification looks like this at the moment:
```
Here's your account verification secret Dean:
XXXXXX
```

It'd be better if the SMS number had a label like `Coder` and/or the SMS text had text like `Here's your account verification secret for Coder.com:`.

**Describe alternatives you've considered**
n/a

**Additional context**
Requested via Discord.

**Comment by RhvsW** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/43533bc8-de9f-4e89-9f7d-f9a64b6254c4-181b4081-cd5f-4cd7-afa3-fc635e6e61d1-v1.png?transparent=1&palette=1&width=246)

**Comment by coadler** [comment]
Fixed :+1:
