### ISSUE TITLE
Language support: HTML should support CSS syntax highlighting in <style>

### ISSUE THREAD

**Issue by deansheather** [codercom/features#32]
**Describe the solution you'd like**
HTML syntax highlighting mode should support CSS syntax highlighting within `<style>` tags.

Currently it looks like this:
![screenshot](https://media.discordapp.net/attachments/467356520711979018/472791498455384074/unknown.png)

**Describe alternatives you've considered**
n/a

**Additional context**
Requested via Discord.

**Comment by pokemonlover1234** [comment]
I'm going to add to this one and say that it should also support JS highlighting in `<script>` tags.

**Comment by Vap0r1ze** [comment]
At the time this feature request was created, script tags did have highlighting for me. However, now they do not.
