### ISSUE TITLE
IDE: work on remote servers

### ISSUE THREAD

**Issue by deansheather** [codercom/features#34]
**Describe the solution you'd like**
Connect to remote servers over SSH and edit files and provide terminal access through the IDE.

**Describe alternatives you've considered**
Mounting remote servers over SFTP onto the Coder container, which doesn't work at the moment as FUSE isn't supported in containers.

**Additional context**
Requested via Discord.

**Comment by yordadev** [comment]
please! <3

**Comment by thewillwilson** [comment]
Simple install script that could install docker and configure an agent would be cool

**Comment by yordadev** [comment]
status? <3

**Comment by deansheather** [comment]
Hi @yordadev, we will update this issue when it's status has changed. Currently it's still just a feature request and not planned from my understanding.

**Comment by yordadev** [comment]
is this planned yet? <3

**Comment by deansheather** [comment]
@yordadev I don't believe this is currently planned. We will post an update here if it becomes a planned feature.

**Comment by yordadev** [comment]
feature bump

**Comment by cottongin** [comment]
any progress on this?

**Comment by baryla** [comment]
still not planned?

**Comment by deansheather** [comment]
As coadler said, this is a planned feature but there is no ETA.

**Comment by Multishifties** [comment]
With the release of our self hosted offering this is now a possibility! @nol166 please close
