### ISSUE TITLE
IDE: be able to leave a project

### ISSUE THREAD

**Issue by deansheather** [codercom/features#35]
**Describe the solution you'd like**
Users that have been added to projects should be able to leave them themselves without being removed from the project by the owner.

Some sort of "leave project" UI.

**Describe alternatives you've considered**
n/a

**Additional context**
Requested via Discord.

**Comment by Multishifties** [comment]
UPDATE: I have an open PR for this.

**Comment by Multishifties** [comment]
@nol166 please close
