### ISSUE TITLE
Mounts: change default NPM global prefix so installing global packages works

### ISSUE THREAD

**Issue by deansheather** [codercom/features#42]
**Is your feature request related to a problem? Please describe.**
Can't install global packages on NPM when using Node mount.

**Describe the solution you'd like**
The `prefix` option in NPM should be set by default to somewhere on the container. This will make installing global packages successful.

**Describe alternatives you've considered**
Installing Node.js and NPM manually via NodeSource repos (works but means you can't use Coder-provided mount).

**Additional context**
Requested/reported via Zendesk `Ticket #341`.

**Comment by kylecarbs** [comment]
Which packages aren't working with a global install?

**Comment by deansheather** [comment]
The customer and I tried `@vue/cli`, which didn't work at the time. Seems to be working now.
