### ISSUE TITLE
Terminal: render UTF-8 characters properly

### ISSUE THREAD

**Issue by deansheather** [codercom/features#47]
**Describe the solution you'd like**
Render UTF-8 characters properly in the terminal (screenshot). They seem to render fine in the IDE.

Screenshot (file contains `(╯°□°）╯︵ ┻━┻`):
![screenshot](https://owo.whats-th.is/20aaf5.png)

**Describe alternatives you've considered**
n/a

**Additional context**
Reported via Zendesk `Ticket #355`.

**Comment by deansheather** [comment]
Zendesk `Ticket #371`: `äöüß`

**Comment by pokemonlover1234** [comment]
The strange layout of the underscores may be related to bugs/#68 in reference to the weird interactions of UTF-8 characters on files.
