### ISSUE TITLE
QA: Feature request - python notebook

### ISSUE THREAD

**Issue by nol166** [codercom/features#49]
Aug 7, 2018 at 5:11:09 PM
### Suggested feature
A user requested support for python notebooks in our IDE. After some research, it appears to be a "command shell for interactive computing in multiple programming languages, originally developed for the Python programming language."

More information can be found here: https://en.wikipedia.org/wiki/IPython

### Zendesk Ticket number
391

**Comment by deansheather** [comment]
[Jupyter works in Coder](https://awau.moe/743504.png)

Instructions:
```
python3 -m pip install jupyter
jupyter notebook --ip=0.0.0.0 --port=8000 --allow-root
```
Then just open the web server in your browser and [copy the token from the terminal](https://awau.moe/3bca41.png) to sign in to Jupyter.

**Comment by deansheather** [comment]
If you want to just install IPython, use `python3 -m pip install ipython`.
