### ISSUE TITLE
Environment backup.

### ISSUE THREAD

**Issue by pokemonlover1234** [codercom/features#50]
**Is your feature request related to a problem? Please describe.**
Currently, whenever it is necessary to reset your container (which has become exceedingly rarer due to the amazing efforts of you guys <3), your installed packages and programs get removed. This is understandable, as it is the express purpose of a reset to return your container to a default state, however it can be annoying if you don't remember the exact setup of packages you had installed and if you have a complex setup, it can take a while to get everything back.

**Describe the solution you'd like**
An option to create an "Environment Backup" and an option to "Restore Environment" from that backup. 
This would allow you to backup your container state (packages and programs, but not projects) at a time when it is working correctly, so that if you break something in the future, you can either completely reset, or revert to that working state so you don't have to go through installing everything all over again.

**Describe alternatives you've considered**
Simply reinstalling and re-configuring everything after the reset, but if you have a complex setup or a lot of stuff, this can take a while.

**Additional context**
Requested via Discord.

**Comment by pokemonlover1234** [comment]
Also, perhaps the ability to backup project state as well.

**Comment by Multishifties** [comment]
We support Docker now for self-hosted instances. This issue is now outdated.

@nol166 please close.
