### ISSUE TITLE
Ability to look at file history for any changes in code

### ISSUE THREAD

**Issue by apark064** [codercom/features#57]
**Is your feature request related to a problem? Please describe.**
Working on a project with multiple users. People tend to delete things or overwrite lines. There is currently no way to return to an earlier state or look at the changes made.

**Describe the solution you'd like**
A file history of the code along with the name of the user who made the change

**Comment by apark064** [comment]
Also I would like to add the ability to jump to the collaborator's position in the file or files they are editing. It would be easier to find what they are editing.

**Comment by deansheather** [comment]
Hi @apark064, as the jump to position thing isn't related to this feature request, I've made another feature request for you (linked above).
