### ISSUE TITLE
SSH into containers

### ISSUE THREAD

**Issue by rvrvrv** [codercom/features#6]
A useful feature would be the ability to SSH into containers. It'd be ideal if we could do that directly within the IDE terminal. Thanks!

**Comment by tilda** [comment]
If you look in the console (devtools) with all levels of logging, there's a log that has the connection info:
![](https://cursed-images.xyz/i/w4qa.png)

**Comment by Xenofuscus** [comment]
It should be much easier to access SSH credentials then via the devtools, so I will forward this to development for consideration.
