### ISSUE TITLE
Docs: more questions for FAQ

### ISSUE THREAD

**Issue by deansheather** [codercom/features#70]
Some commonly asked questions in the Discord server and on Zendesk:
- Why is my application not showing on Cdr.co => try listening on `0.0.0.0`
- Common troubleshooting steps for problems
- How to get a request/container/workspace/project ID

**Comment by rvrvrv** [comment]
[Tech FAQs](https://docs.coder.com/docs/tech-faqs) -- This new page will expand greatly during the next week.
