### ISSUE TITLE
Add collaboration accept buttons inside of Coder.com

### ISSUE THREAD

**Issue by NGTmeaty** [codercom/features#77]
**Is your feature request related to a problem? Please describe.**
You have to accept invitations to new projects on your email.There should be a page inside of Coder or a notifications which explains when you've been invited to a team. 

**Describe the solution you'd like**
Invitation notices and accept buttons inside of Coder.com. 

**Describe alternatives you've considered**
Email as it is now. 

**Additional context**
Requested on Discord by lilrex

**Comment by nol166** [comment]
This is coming very soon
