### ISSUE TITLE
Rename file from file tree

### ISSUE THREAD

**Issue by JeremyJaydan** [codercom/features#8]
**Is your feature request related to a problem? Please describe.**
I can't seem to find a way to re-name a file from the file tree.

**Describe the solution you'd like**
Ability to rename a file from the file tree.

**Describe alternatives you've considered**
Using the terminal works fine for renaming (`mv target_file.ext new_name.ext`)

**Comment by nhuebecker** [comment]
Hey @JeremyJaydan in the IDE if you right-click a file or hover and click F2 in the file tree you should be able to rename it. Could you send a screenshot of what you are trying to do, if this doesn't help.

Happy Coding 👨‍💻!

**Comment by JeremyJaydan** [comment]
@nhuebecker No context menu shows when I right click on a file, using F2 works though, thanks!

**Comment by nhuebecker** [comment]
Yeah, I believe this was logged in [coder/bugs #8](https://github.com/codercom/bugs/issues/8)
