### ISSUE TITLE
Autosave

### ISSUE THREAD

**Issue by xaanit** [codercom/features#80]
**Is your feature request related to a problem? Please describe.**
I come from Intellij IDEA and it has an auto save feature, you never have to ctrl +save. It really helps you save a lot of time and pain if you accidentally hit the wrong keybind or forget to save.

**Describe the solution you'd like**
Saving after every keystroke would be nice but that's difficult so maybe after you stop typing, or on a timer.

**Describe alternatives you've considered**
Ctrl + s

**Additional context**
This would be a fantastic feature. It'd help a lot of newer developers who forget to save.

**Comment by nhooyr** [comment]
see https://github.com/codercom/features/issues/126
