### ISSUE TITLE
IDE: auto-indenting in some languages

### ISSUE THREAD

**Issue by deansheather** [codercom/features#81]
**Describe the solution you'd like**
When you click enter, it should automatically indent to where it should be. Currently when you click enter, the new line starts with the same indent as the previous line and does not intelligently indent to match functions etc.

**Describe alternatives you've considered**
n/a

**Additional context**
Requested via Zendesk `Ticket #667`.

**Comment by deansheather** [comment]
Affects Python, HTML. Please comment with any other languages.

**Comment by jaymeramsay** [comment]
```Zendesk ticket 1026``` for Python.
