### ISSUE TITLE
Support: increase description character limit in the feedback menu

### ISSUE THREAD

**Issue by deansheather** [codercom/features#83]
**Describe the solution you'd like**
Increase the maximum characters in the feedback description box from 256 to something bigger. Reporting issues that take a lot of characters to explain currently have to be sent via email or not explained properly.

**Describe alternatives you've considered**
Email support@coder.com.

**Additional context**
Requested via Zendesk `Ticket #685`.

**Comment by Multishifties** [comment]
Was increased to 1024 characters with https://github.com/codercom/frontend/pull/199/commits/19d4c6035dfbe15e85e4b74cc02af90eef80ac68

@nol166 please close
