### ISSUE TITLE
UX: Remember Me Option for Login

### ISSUE THREAD

**Issue by jaentwistle** [codercom/features#9]
Submitted via Zendesk 

Add a "Remember Me" option for login to reduce frustrations and inconvenience of having to log in repeatedly.

**Comment by Xenofuscus** [comment]
Forwarded to development for further consideration.

**Comment by lobsterhands** [comment]
If a user is authenticated, the Login button will redirect the user to the dashboard.

**Comment by deansheather** [comment]
@lobsterhands should the signup button still be displayed on the homepage then? I think it'd be better to replace the login and signup buttons on landing with a "Dashboard" button if the user is authenticated.
